---
title: "`r paste('Groundwater Observatory Daily Report:', Sys.Date())`"
output: pdf_document
---

# Battery Status of Monitoring Units

```{r, echo = FALSE, message=FALSE, error=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
library(readr)
library(leaflet)
library(ggplot2)
library(ggmap)
library(sp)

# load and format battery life df
battery_life_df    <- read_rds("battery_life_df.rds")
battery_life_df$id <- substr(battery_life_df$id, 2, 7)

# color coded table
battery_life_df %>% 
  mutate(
    bat = cell_spec(bat, color = ifelse(bat >= 80,"#008000", ifelse(bat < 80 & bat >= 70, "#FFA500", "#ff0000") ))
  ) %>% 
  kable(escape = FALSE, col.names = c("Level Sender ID #", "Battery Life (%)", "Unit Type")) %>% 
  kable_styling(latex_options = "striped", full_width = TRUE, position = "center", font_size = 20)
```


```{r, echo = FALSE, message=FALSE, error=FALSE, warning=FALSE}
# ggplot of battery life at LS, LL, and BaroL
cs_coords <- data.frame(lat = c(38.31263, 38.30505, 38.30488, 38.29666, 38.30271, 38.2967, 38.29174, 38.29183, 38.30517, 38.30965, 38.30967, 38.2967, 38.30101), 
                        lng = c(-121.379, -121.381, -121.369, -121.374, -121.379, -121.379, -121.382, -121.391, -121.391, -121.376, -121.384, -121.382, -121.384), 
                        Location = c("MW2", "MW9", "MW11", "MW20", "OnetoAg", "MW19", "MW23", "MW22", "MW7", "MW5", "MW3", "MW17", "MW13")
                        )
cs_coords$id <- as.character(c(NA, 284220, 284216, NA, NA, 284214, NA, 284217, NA, 283687, NA, NA, NA))

df <- left_join(battery_life_df, cs_coords, by = "id") %>% filter(!is.na(lat))

dat    <- df[, 1:3]
coords <- df[, c("lat", "lng")]

spdf <- SpatialPointsDataFrame(coords = coords, data = dat, proj4string = CRS("+init=epsg:4326 +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))

plot(spdf)

```


***  


# Last 30 days of Received Data
```{r, echo = FALSE, message=FALSE, error=FALSE, warning=FALSE}
# ggplot of last 30 days of data
ggp <- read_rds("ggp.rds")
ggp
```

